---
title: "Exploratory Analysis of Injury Data"
output: pdf_document
params:
  injd: NA
header-includes:
  - \usepackage{booktabs}
  - \usepackage{array}
  - \usepackage{float}
  - \floatplacement{figure}{H}
---


```{r setup, echo = FALSE}
opts_chunk$set(echo=FALSE, results='asis',
               fig.path='tempFiguresForKnitrReport/', 
               fig.width=9, fig.height=7)
```

```{r params}
injd <- params$injd
df_expo <- attr(params$injd, "data_exposures")
df_inj <- attr(params$injd, "data_injuries")
```

## Overview of injuries

```{r gg_injphoto, fig.width = 9.5, height = 6.8, fig.cap = "Timeline of the football players' follow-up period together with the injuries they sustained", fig.pos="H"}
gg_injphoto(injd, by_date = "1 year", fix = TRUE)
```

Below, the main summary statistics of the chosen cohort:

```{r overview_table}
tot_players <- nlevels(df_expo$player)
tot_players_inj <- nlevels(df_inj$player)
tot_players_injpercent <- round(tot_players_inj/tot_players*100, 2)
tot_expo <- sum(df_expo$time_expo)
median_expo_player <- df_expo %>%
  group_by(player) %>%
  mutate(total_expo_player = sum(time_expo)) %>%
  ungroup() %>%
  summarise(median_expo_player = median(total_expo_player)) %>%
  pull(median_expo_player)
tot_injuries <- nrow(df_inj %>% select(player, date_injured) %>% unique()) ## this should be given as it is (the uniqueness I mean. May be add this to test.R in "injurytools")
tot_days_lost <- sum(df_inj$days_missed)

data.frame(tot_players,
           tot_playerse_inj = paste0(tot_players_inj," (", tot_players_injpercent, "%)"),
           players_injury_free =  paste0(tot_players - tot_players_inj, " (", 100-tot_players_injpercent, "%)"),
           row.names = "TOTAL") %>%
  kable(col.names = c("N players",
                      "N players injured (%)",
                      "N players injury free (%)"),
        format = "latex", booktabs = T) %>% 
  row_spec(0, bold = TRUE) %>% 
  column_spec(column = 2:4, width = "4.8cm")
```

```{r injsummary}
injds <- injsummary(injd, quiet = TRUE)
```

```{r}
# format the table for total incidence and burden main columns
injds[[2]] %>% 
  select(1:5) %>% 
  data.frame(row.names = "TOTAL") %>% 
  kable(digits = 2,
        col.names = c("N injuries", "N days lost",
                      "Total exposure", "Incidence", "Burden"),
        row.names = TRUE,
        format = "latex", booktabs = T)
```


```{r}
injds_tot_cis <- injds[[2]] %>% 
  select(4:last_col()) %>% 
  data.frame(row.names = "TOTAL")
injds_tot_cis$ci_injincidence <- paste0("[", round(injds_tot_cis$injincidence_lower, 1),
                                    ", ",round(injds_tot_cis$injincidence_upper, 1), "]")
injds_tot_cis$ci_injburden <- paste0("[", round(injds_tot_cis$injburden_lower, 1),
                                    ", ",round(injds_tot_cis$injburden_upper, 1), "]")

conf_level <- attr(injds, "conf_level")*100
injds_tot_cis %>% 
  select(1, 9, 2, 10) %>% 
  kable(digits = 2,
        col.names = c("Incidence",  paste0("CI", conf_level, "% for \\(I_r\\)"), 
                      "Burden", paste0("CI", conf_level, "% for \\(I_{br}\\)")),
        format = "latex", booktabs = T) 
```

# Playerwise injury summary statisics

- **Who is the most injured player?**

```{r q1}
injds[[1]] %>%
  filter(max(ninjuries) == ninjuries) %>%
  select(Player = player, "Number of injuries" = ninjuries) %>%
  kable(format = "latex", booktabs = TRUE) %>%
  row_spec(0, bold = TRUE)
```

- **Who is the player with more days lost?**

```{r q2}
injds[[1]] %>% 
  filter(max(ndayslost) == ndayslost) %>% 
  select(Player = player, "Number of days lost" = ndayslost) %>% 
  kable(format = "latex", booktabs = T) %>% 
  row_spec(0, bold = TRUE) 
```

- **Who is the player with highest injury incidence?**

```{r q3}
injds[[1]] %>%
  filter(max(injincidence) == injincidence) %>%
  select(Player = player, "Injury incidence" = injincidence) %>%
  kable(digits = 2, format = "latex", booktabs = T) %>%
  row_spec(0, bold = TRUE) 
```

- **Who is the player with highest injury burden?**

```{r q4}
injds[[1]] %>%
  filter(max(injburden) == injburden) %>%
  select(Player = player, "Injury burden" = injburden) %>%
  kable(digits = 2, format = "latex", booktabs = T) %>%
  row_spec(0, bold = TRUE)
```



```{r ranking_table}
## Following table shows playerwise injury summary statistics (first 10 and last 10 players):
  
# kable(injds %>% arrange(desc(injburden)),
#       format = "html",
#       col.names = c("Player", "Number of injuries", "Number of days lost", "Total exposure", "Injury incidence", "Injury burden")) %>%
#   row_spec(0, bold = TRUE) %>%
#   column_spec(2:6, width = "2.2cm") %>%
#   column_spec(1, width = "3cm")
# injds[[1]] %>% 
#   arrange(desc(injincidence)) %>% # sort by decreasing order of injincidence
#   slice(1:10, n()-9:n()) %>% 
#   kable(digits = 2, col.names = c("Player", "N injuries", "N days lost",
#                                   "Total exposure", "Incidence", "Burden"))
```

Grafically:

```{r ranking_fig, echo = FALSE, fig.width = 9.5, fig.height = 7.4, fig.cap = "Barplots of each players' injury incidence (left) and injury burden (right) in descending order", fig.pos = "H"}
p1 <- gg_injbarplot(injds, type = "incidence")
p2 <- gg_injbarplot(injds, type = "burden")
grid.arrange(p1, p2, nrow = 1)  
```


# Risk matrices

```{r, fig.width = 9.5, fig.height = 5, fig.cap = "Risk matrix, that displays injury incidence (likelihood) against injury burden (severity), according to injury type", fig.pos = "H"}
injds_pervar <- injsummary(injd, var_type_injury = "injury_type", quiet = T)
gg_injriskmatrix(injds_pervar, var_type_injury = "injury_type",
                 title = "Risk matrix according to injury type")
```


```{r, fig.width = 9.5, fig.height = 5, fig.cap="Risk matrix, that displays injury incidence (likelihood) against injury burden (severity), according to the location of the injury", fig.pos = "H"}
injds_pervar2 <- injsummary(injd, var_type_injury = "injury_loc", quiet = T)
gg_injriskmatrix(injds_pervar2, var_type_injury = "injury_loc",
                 title = "Risk matrix according to the location of the injury")
```



# Availability

```{r, fig.cap = "Injured and injury free player proportions in a monthly basis", fig.pos = "H"}
gg_injpolar(injd, by = "monthly",
            title = "Proportion of injured and available\n players in each month") +
  scale_fill_manual(name = "Type of injury", 
                    values = c("seagreen3", "red3"))
```
<!-- ## Questions: are there differences regarding age/position/season? -->